/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngmeta.module';
import * as i2 from '@angular/common';
import * as i3 from './ngmeta.service';
import * as i4 from '@angular/router';
export const NgMetaModuleNgFactory:i0.NgModuleFactory<i1.NgMetaModule> = i0.ɵcmf(i1.NgMetaModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.NGMeta,i3.NGMeta,[i4.Router]),
          i0.ɵmpd(512,i1.NgMetaModule,i1.NgMetaModule,[i3.NGMeta])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21pY2hhZWxzb2xhdGkvRG9jdW1lbnRzL3dvcmtzcGFjZS9uZ21ldGEvc3JjL25nbWV0YS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWljaGFlbHNvbGF0aS9Eb2N1bWVudHMvd29ya3NwYWNlL25nbWV0YS9zcmMvbmdtZXRhLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
